### ISSUE TITLE
Exif::format(), eine Idee

### ISSUE THREAD

**Issue by akrys** [FriendsOfREDAXO/mediapool_exif#12]
Ich habe schon eine Funktion geschrieben mit der man einen bestimmten Index der Exif-Rohdaten holen kann.

Idee wäre nun, eine weitere Funktion zu schreiben, mit der man "formatierte" Daten holen kann.
(Die Idee ist noch etwas unsortiert, ich wollte sie erstmal nur vor dem Vergessen retten)

z.B. könnte man die Geo-Koordinaten in verschiedenen Formaten holen:
`$exif->format('geo', 'dec')` (decimal)
Ergebnis:
\- lat: 51.1109221
\- long: 8.6821267
-> diese Funktion könnte bspw. beim Einlesen der Geo-Daten einfach aufgerufen werden.

`$exif->format('geo', 'deg')` (degree)
Ergebnis:
\- lat: 51° 06' 39.32" N
\- long: 8° 40' 55.656 E

Gleiches könnte man z.B. den Fotowerten machen:
`$exif->format('fotovalues','raw')`
Ergebnis:
\- exposure: 1/60
\- f: 28/5
\- iso: 100
\- focal: 49/1

`$exif->format('fotovalues','readable')`
Ergebnis:
\- exposure: 1/60s
\- f: f/5.6
\- iso: 100
\- focal: 49mm

Idee wäre, die Funktion als Factory zu verwenden, so dass die Berechnungen selbst in eigenen Klassen passieren, die man auch wiederverwenden kann. 

Ideen für die Parameter:
1. Klassename
2. Methodenname

Wenn die Klasse bzw. die Funktion nicht existiert, kann eine Exception geworfen werden. Als Hinweis, dass man das Format doch gerne selbst umzusetzen und als PR bereit stellen darf 🙂

Je nach Klasse müssten verschiedene Daten aus den Rohdaten übergeben werden.
- Geo bräuchte `GPSLatitude`,`GPSLatitudeRef`, `GPSLongitude`, `GPSLongitudeRef`
- FotoValues bräuchte `ExposureTime`, `FNumber`, `ISOSpeedRatings`, `FocalLength`
- "GeoEingelesen" hätte dann max. `med_lat`, `med_long` aus `media` zur Verfügung um dann die `deg`-Funktion aufzurufen.

Vielleicht sollte man den Format-Klassen einfach die ganzen Rohdaten geben, und die jeweilige Klasse ist dafür verantwortlich, was sie sich nimmt.

Die Umrechnung von `dec` zu `deg` könnte man noch gesondert auslagern und aufrufbar machen.

Wie gesagt: es ist erstmal eine unsortierte Idee.

**Comment by tbaddade** [comment]
@akrys Ich hatte gestern dieses Issue eröffnet um Ideen für ein Geo-AddOn zu sammeln, u.a. auch um Geo-Daten umrechnen zulassen.

**Comment by akrys** [comment]
Ah OK, hier war nur ein PR zur Umrechnung der EXIF-Koordinaten in Dezimal-Koordinaten drin. Daher die Idee, dass man das vielleicht lesbarer formatieren könnte. Somit ein Beispiel, dass es für gleiche Daten verschiedene Formate geben könnte.

Wenn man aber bestimmte Formatierungen woanders hin auslagern kann: Umso besser. Dann brauch ich mir hier keinen Kopf drum zu machen. Dann kann man hier z.B. nur die Dezimal-Werte liefern. Wer das anders formatieren möchte, nutzt dann halt das Geo-AddOn.
Finde ich wunderbar.

**Comment by tbaddade** [comment]
> Somit ein Beispiel, dass es für gleiche Daten verschiedene Formate geben könnte.

Was ich meinte, dass das Umrechnen durch dieses Geo-AddOn passieren kann und du dieses dann in dem Exif AddOn nutzen könntest. Die formatierte Ausgabe kannst du dann dennoch ausliefern, wenn du magst. 

Somit müssten Vendoren oder PHP Klassen nur einmal geladen/geschrieben und nicht von jedem einzelnen AddOn mitgebracht werden.

**Comment by akrys** [comment]
Die Umsetzung Exif zu Dezimal ist hier ja bereits umgesetzt worden:
https://github.com/FriendsOfREDAXO/mediapool_exif/blob/fe340e7b086107f87de0462effb29edca0889f32/lib/rex_mediapool_exif.php#L296-L323

Daher wäre dann die Frage, ob das ins Geo-AddOn ausgelagert werden sollte. Kann man natürlich machen. Allerdings glaube ich, dass die Geo-Daten in Exif schon etwas esoterisch gespeichert sind. Daher mein Gedanke, dass das hier schon gut aufgehoben ist. Umrechnungen der Dezimal-Koordinaten kann ja immer noch über das Geo-AddOn passieren. Das ist da vielleicht sogar günstiger untergebraucht. Und man müsste nicht unbedingt EXIF von Geo abhängig machen. Geo-Daten sind ja nicht das einzige, was es in den Exif-Daten gibt. (Auch wenn eine der üblichsten Anwendungsbereiche ist)

**Comment by tbaddade** [comment]
Mach bitte wie du es für das Exif AddOn richtig hälst. Ich wollte nur auf das andere AddOn hinweisen (was auch erst einmal umgesetzt werden muss).
