### ISSUE TITLE
Daten werden untere Verwendung von "Uploader" nicht automatisch übernommen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mediapool_exif#18]
https://github.com/FriendsOfREDAXO/uploader

(Mit "Multiupload" geht es)

**Comment by akrys** [comment]
Solange Uploader die Mediapool-EPs  ```MEDIA_ADDED``` und ```MEDIA_UPDATED``` triggert, sollte es kein Problem geben.
Wenn nicht erkannt wird, dass eine Datei im Medienpool bearbeitet bzw. hinzugefügt wird, geht die Aktion hier (wie auch in anderen Addons, die auf diese EPs hören) natürlich vorbei. Das habe ich gerade auf die Schnelle im Uploader-Addon nicht prüfen können.

**Comment by IngoWinter** [comment]
Uploader ruft [rex_mediapool_syncFile()](https://github.com/FriendsOfREDAXO/uploader/blob/master/lib/uploader_iw_upload_handler.php#L119) auf, wodurch rex_mediapool_saveMedia() in der MEDIA_ADDED registriert ist.
Ob es an der Verkleinerung liegt kannst du ja schnell testen.

**Comment by akrys** [comment]
Ich hab mir das mal angesehen. Er scheint das tatsächlich aufzurufen. Auch die Update-Statements zum Eintragen der Daten werden ausgeführt.

Nach der Ausführung der Extensionpoints ```MEDIA_ADDED``` oder ```MEDIA_UPDATED``` wird im Uploader ```uploader_meta::save($success);``` aufgerufen. Dadurch werden die Meta-Daten in die Tabelle ```rex_media``` geschrieben. Und zwar die Daten, die vor dem Aufruf der Extensionpoints drin gestanden haben. Die Daten, die in den Extensionpoints ermittelt und geschrieben wurden, werden somit mit den Daten überschreiben, die vorher ermittelt wurden.

Ich weiß gerade nicht, wie man das umgehen kann.

**Comment by akrys** [comment]
Da die Daten, die in die Tabelle hinein geschrieben werden später vom uploader wieder überschrieben werden, kann ich an der Stelle leider nicht viel tun.
