### ISSUE TITLE
Funktioniert nicht Verwendung des imageoptimizer Plugins 

### ISSUE THREAD

**Issue by lexplatt** [FriendsOfREDAXO/mediapool_exif#20]
Beim Hinzufügen neuer Medien schneidet das imageoptimizer Plugin alle Exif-Daten weck

**Comment by akrys** [comment]
Ich hatte gerade etwas Zeit ein wenig zu testen.

Also:

- Das _ImageOptimezerPlugin_ habe ich im _Multiupload_-Addon gefunden. (Nur damit wir vom gleichen Addon sprechen)
- Dieses schneidet jedoch keine Daten weg (was mich etwas irritiert hat)
- Das ebenfalls dort mitgelieferte _upload_precompressor_-PlugIn schneidet aber alles weg. Der ist also der Übeltäter…

Kommen wir zu den schlechten Nachrichten, denn der _upload_precompressor_ registriert den ExtensionPoint `MEDIA_ADDED` via `rex_extension::EARLY` also vor allen anderen PlugIns.

Daraufhin habe ich testweise _mediapool_exif_ den ExtensionPoint ebenfalls via `rex_extension::EARLY` registriert. Hätte ja sein können, dass _mediapool_exif_ trotz  gleicher Prio früher dran wäre. In beide Funktionen habe dann mal testweise geloggt, dass sie aufgerufen werden, so kann man die Reihenfolge in etwa nachvollziehen. (s. Bild)

<img width="1419" alt="Bildschirmfoto_2021-05-04_um_22_54_28" src="https://user-images.githubusercontent.com/6718126/117071049-dba42280-ad2e-11eb-94f9-4fabe61d007c.png">

Ergebnis:
Was soll ich sagen: Auch mit `rex_extension::EARLY` ist der _upload_precompressor_  leider vorher dran. Heißt: Es wird erst weggeschnitten und danach analysiert, egal, wie früh ich mich da einklinke.

Daher kann ich da vorerst nichts weiter unternehmen 🙁 (Und muss das Ticket unverrichteter Dinge schließen)

Ich belasse den Aufruf von `MEDIA_ADDED` auch erstmal auf `rex_extension::LATE`. Aus dem Commit dbdb071b37701511b3349e46630702453a1ddfae lässt sich auf Anhieb nicht so ohne Weiteres herauslesen, warum der Ausführungszeitpunkt auf `rex_extension::LATE` gesetzt wurde. Ich nehme mal an, es gab damals einen Grund dafür.
