### ISSUE TITLE
Warnings: Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by rolandsee** [FriendsOfREDAXO/mediapool_exif#22]
In meinen Projekten häufen sich die Warnings im log (Warning: Invalid argument supplied for foreach() in redaxo/src/addons/mediapool_exif/lib/MediapoolExif.php on line 215).
Dieser Eintrag entstand z.B. beim Aktualisieren eines jpg-Bildes.
Wenn Kunden sehr viel im Medienpool arbeiten, wird das log-File schnell sehr lang und unübersichtlich.

PHP 7.4. Redaxo 5.12; Mediapool_exif 2.0; auch sonst alles auf dem aktuellsten Stand.

![image](https://user-images.githubusercontent.com/4113894/116874389-8cb89900-ac19-11eb-8170-a025aeb0121d.png)

**Comment by rolandsee** [comment]
Hmm, die Warning tritt bei mir nach wie vor auf.
![image](https://user-images.githubusercontent.com/4113894/158137238-1f141ef2-d2ee-4860-a3e9-2ab5b803e908.png)
Wurde hier schon ein Fix implementiert?

**Comment by akrys** [comment]
Oh, Sorry. Ist komplett untergegangen. Ich schaue mal, dass ich morgen Abend ein Release fertig mache.
