### ISSUE TITLE
mediapool exif wirft einen Whoops beim Umstellen der DB auf utf8mb4

### ISSUE THREAD

**Issue by madiko** [FriendsOfREDAXO/mediapool_exif#26]
**Description / Beschreibung**

Hallo, als ich soeben die REX-Datenbank von utf8 auf utf8mb4 umstellen wollte, bekam ich einen Whoops. 

Die **Lösung** war, mediapool_exif kurz zu deinstallieren – das Setup neu zu durchlaufen (Datenbank aktualisieren) und dann mediapool_exif wieder zu installieren. 

Bitte schaut mal, ob dieser Umweg vermieden werden kann. Stacktrace unten.

**Affected versions / Verwendete Versionen**

REDAXO: 5.14.1
PHP: 7.4.33
Database: MariaDB 10.6.11
Browser: FireFox 107.0.1 (32-Bit)
AddOns: (bitte nachfragen, wenn hier mehr Infos benötigt werden)

**Did it whoops? / Whoops erhalten?**

**Error:** Call to undefined function rex_metainfo_add_field()
**File:** redaxo/src/addons/mediapool_exif/install.php
**Line:** 8

<details>
<summary>Stacktrace</summary>

| Function                               | File                                            | Line     |
| -------------------------------------- | ----------------------------------------------- | -------- |
| require                                | redaxo/src/core/lib/packages/package.php        | 280      |
| rex_package->includeFile               | redaxo/src/core/lib/packages/manager.php        | 143      |
| rex_package_manager->install           | redaxo/src/core/lib/packages/addons/manager.php | 27       |
| rex_addon_manager->install             | redaxo/src/core/lib/setup/import.php            | 281      |
| rex_setup_importer::reinstallPackages  | redaxo/src/core/lib/setup/import.php            | 32       |
| rex_setup_importer::updateFromPrevious | redaxo/src/core/pages/setup.php                 | 211      |
| include                                | redaxo/src/core/lib/be/controller.php           | 482      |
| rex_be_controller::{closure}           | redaxo/src/core/lib/util/timer.php              | 57       |
| rex_timer::measure                     | redaxo/src/core/lib/be/controller.php           | 490      |
| rex_be_controller::includePath         | redaxo/src/core/lib/be/controller.php           | 422      |
| rex_be_controller::includeCurrentPage  | redaxo/src/core/backend.php                     | 239      |
| require                                | redaxo/src/core/boot.php                        | 143      |
| require                                | redaxo/index.php                                | 9        |

</details>
<details>
<summary>System report (REDAXO 5.14.1, PHP 7.4.33, MariaDB 10.6.11)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.14.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.4.33                         |
|       OPcache | yes                            |
|        Xdebug | no                             |
|       Warning | Die verwendete PHP-Version 7.4.33 wird nicht mehr vom Hersteller gepflegt und sollte aktualisiert werden. |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.6.11 |
| Character set | utf8            |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Firefox/107.0 |
|      Protocol | HTTP/2.0      |
|         HTTPS | yes           |

| Packages                  |            |
| ------------------------: | :--------- |
|              accessdenied | 2.0.2      |
|                   adminer | 1.9.2      |
|                    backup | 2.8.2      |
|               be_password | 2.0.1      |
|                  be_style | 3.1.0      |
|           be_style/redaxo | 3.1.0      |
|                   bloecks | 3.1.1      |
|          bloecks/cutncopy | 3.1.1      |
|            bloecks/status | 3.1.1      |
|              cache_warmup | 4.0.0      |
|     configurator_indexing | 1.0.0      |
|         configurator_news | 1.0.0      |
|                   cronjob | 2.9.0      |
|    cronjob/article_status | 2.8.1      |
|   cronjob/optimize_tables | 2.8.1      |
|                     debug | 1.2.2      |
|                 developer | 3.9.0      |
|           emailobfuscator | 3.0.0      |
|                 enjoywork | 1.0.0      |
|                focuspoint | 4.0.2      |
|                   install | 2.10.0     |
|              lightgallery | 0.4.3      |
|                  markitup | 3.7.1      |
|    markitup/documentation | 1.1.0      |
|                    mblock | 3.4.6      |
|             media_manager | 2.13.0     |
| media_manager_autorewrite | 2.0.1      |
|                 mediapool | 2.12.0     |
|            mediapool_exif | 2.0.1      |
|                  metainfo | 2.9.0      |
|                     mform | 7.2.0      |
|                 phpmailer | 2.11.2     |
|                   project | dev        |
|                     sprog | 1.3.0      |
|                 structure | 2.14.1     |
|         structure/content | 2.14.1     |
|         structure/history | 2.14.1     |
|         structure/version | 2.14.1     |
|               tablesorter | 0.1.1      |
|                     theme | 1.3.3      |
|                       url | 2.0.2      |
|               usage_check | 2.3        |
|                     users | 2.9.0      |
|                     yform | 4.0.2      |
|               yform/email | 4.0.2      |
|             yform/manager | 4.0.2      |
|                yform/rest | 4.0.2      |
|               yform/tools | 4.0.2      |
|             yform_geo_osm | 1.2.6      |
|     yform_spam_protection | 1.2.2      |
|           yform_usability | 2.0.5      |
|                  yrewrite | 2.9.1      |
|           yrewrite_scheme | 3.6.2      |

</details>

**Comment by madiko** [comment]
Hallo Axel, meine Systeme sind nun komplett auf UTF8 umgestellt. Von daher kann ich das aktuell nicht (mehr) prüfen. Es war auch eher als Hinweis für Euch gedacht. Tut mir leid, dass ich da jetzt nicht besser unterstützen kann. Sollen wir den Issue damit schließen?

**Comment by akrys** [comment]
Dann können wir es tatsächlich schließen, denke ich
