### ISSUE TITLE
Funktion mit AddOn Uploader

### ISSUE THREAD

**Issue by polarpixel** [FriendsOfREDAXO/mediapool_exif#28]
Das AddOn ist sehr hilfreich, vielen Dank!
Allerdings funktioniert es nicht im Zusammenspiel mit dem Uploader-AddOn (das aus meiner Sicht essenziell ist, da man oft mehrere Dateien auf einmal hochladen will).
https://github.com/FriendsOfREDAXO/uploader
Wäre es möglich, hier ein Zusammenspiel zu ermöglichen?

**Comment by akrys** [comment]
Ich glaube, ich muss mir demnächst mal ein aktuelles Redaxo-System aufsetzen. Hab ich zwar schon seit einiger Zeit vor, komme nur nicht dazu ;-)

**Comment by polarpixel** [comment]
Würde mich freuen. :-)
Ein Kunde fragt aktuell auch nach diesem Feature. Mal schauen, vielleicht will er ja auch was finanzieren ...

**Comment by akrys** [comment]
Ich setze es mal auf die Urlaubs-Todo-Liste. (KW 44)
Jetzt hab ich mir selbst auch genug Druck gemacht, es auch zu tun ;-)

**Comment by akrys** [comment]
Ich hab es gerade mal ausprobiert. Ich lade mehrere Dateien via Uploader-Feld hoch.
Danach sind alle Daten – wie erwartet – eingelesen.

Was genau funktioniert nicht?

**Comment by akrys** [comment]
Ich hatte noch einen Fehler gefunden, wenn gar keine Daten vorhanden sind:
```
FriendsOfRedaxo\addon\MediapoolExif\Format\FormatInterface::__construct(): Argument #1 ($data) must be of type array, null given
```

Das liegt aber daran, dass ich bei der Umsetzung immer schon Daten eingelesen hatte. Ich hatte nämlich auch eine Möglichkeit geschaffen, die Daten auch im Nachhinein noch einlesen zu können:
```bash
redaxo/bin/console mediapool_exif:read
```

Damit ist der Fall, dass gar keine Daten da sind, völlig aus meinem Blickfeld verschwunden.

Das hat aber weniger mit dem Zusammenspiel mit `uploader` zu tun.

**Comment by akrys** [comment]
Hab mich nochmal genauer damit befasst und hatte gestern nur die `exif`-Spalte gecheckt. Dass die anderen Felder überschreiben wurde hatte nicht mehr gesehen.

Lösungsvorschlag sieht nun wie folgt aus:

Im `metainfo`-Addon wird ein Flag-Parameter an die Funktion `fetchRequestValues`, das leere Werte ignoriert werden dürfen:
https://github.com/redaxo/redaxo/pull/5852

Uploader ruft diese Funktion mit dem Wert `false` auf, um das Überschreiben zu verhindern:
https://github.com/FriendsOfREDAXO/uploader/pull/78
